name: github-actions-demo-TestExecute

on:
  workflow_dispatch:  # Trigger manually from GitHub UI
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # runs-on: [self-hosted, windows, tc-001]  # Runs on your self-hosted Windows runner
    runs-on: [self-hosted, windows, azure-vm001]  # Runs on your self-hosted Windows runner

    env:
      ProjectPath: '${{ github.workspace }}\WebTesting\WebTesting.pjs'  # Define the project path
      AccessKey_TC: ${{ secrets.TEST_EXECUTE_ACCESS_KEY }}  # Assuming you store the Access Key in GitHub Secrets
      InstallerPath: '${{ github.workspace }}\TE.exe'
      LOG_DIR: 'C:\actions-runner\logs'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Job Startup
        run: |
          echo "Starting job [Event=${{ github.event_name }}]"
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        
      - name: Show working folder content
        run: dir
        shell: cmd

      - name: Check if TestExecute is already installed
        run: |
          if exist "${{ env.InstallerPath }}" (
            echo "TestExecute installer already exists, skipping download."
          ) else (
            echo "TestExecute installer not found, proceeding with download."
            powershell -Command "Invoke-WebRequest -Uri '${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}' -OutFile '${{ github.workspace }}\TE.exe'"
          )
        shell: cmd

      - name: Install TestExecute
        run: |
          if exist "${{ env.InstallerPath }}" (
            echo "Installing TestExecute..."
            "${{ env.InstallerPath }}" -SilentInstall
          ) else (
            echo "Installer file TE.exe not found, skipping installation."
          )
        shell: cmd

      - name: Env Variable for TestExecute bin folder
        run: set PATH_TE="${{ vars.TEST_EXECUTE_BIN }}"
        shell: cmd
        
      - name: Prepare Logs Folder
        run: |
          if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
        shell: cmd

      - name: Verify project path
        run: |
          echo Current directory: %cd%
          dir /s WebTesting.pjs
        shell: cmd

      - name: Close Microsoft Edge
        run: |
          echo Checking if Microsoft Edge is running...
          tasklist /FI "IMAGENAME eq msedge.exe" 2>NUL | find /I "msedge.exe" >NUL
          if %ERRORLEVEL%==0 (
            echo Closing Microsoft Edge...
            taskkill /F /IM msedge.exe
          ) else (
            echo Microsoft Edge is not running, nothing to close.
          )
        shell: cmd

      - name: Clean up old logs
        run: |
          if exist "${{ env.LOG_DIR }}" (
            echo Deleting old log files...
            del /q "${{ env.LOG_DIR }}\*"
          )
        shell: cmd

      - name: Run TestExecute
        run: |
          echo Starting TestExecute...
          "C:\Program Files (x86)\SmartBear\TestExecute 15\x64\Bin\TestExecute.exe" "${{ env.ProjectPath }}" /r /e /AccessKey:${{ env.AccessKey_TC }} /SilentMode /Timeout:1200 /ns /ErrorLog:"${{ env.LOG_DIR }}\error.log" /ExportLog:"${{ env.LOG_DIR }}\runlog.html" /ExportSummary:"${{ env.LOG_DIR }}\runlog.xml" /shr:"${{ env.LOG_DIR }}\shared-repo-link.txt" /shrn:LogFromGitHubAction /shrei:7
        shell: cmd

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: testexecute-logs
          path: ${{ env.LOG_DIR }}
        
      - name: Verify logs
        run: |
          echo "Current directory: %cd%"
          dir ${{ env.LOG_DIR }}
        shell: cmd
