name: Run Desktop UI Tests with TestExecute

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up environment
        run: |
          echo "Setting up environment variables"
          # Set any necessary environment variables here (if needed)
          
      - name: Run TestExecute tests
        run: |
          # Command to run TestExecute with your test project
          "C:\Program Files (x86)\SmartBear\TestExecute 15\x64\Bin\TestExecute.exe" "C:\Path\To\Your\ProjectSuite.pjs" /r /p:TestProject
          
      - name: Collect and upload test results
        run: |
          # Collect TestExecute results (customize this to match your setup)
          echo "Collecting test results"
          # Assuming the results are in a folder, for example "C:\Path\To\Results"
          upload-artifact --name test-results --path "C:\Path\To\Results"
