name: Run TestExecute Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Execute SmartBear TestExecute
    runs-on: [self-hosted, Windows, x64]  # Labels of your Windows runner

    env:
      # PROJECT_PATH: "C:\\actions-runner\\_work\\TC-108943\\TC-108943\\WebTesting\\WebTesting.pjs"
      PROJECT_PATH: "C:\\actions-runner\\_work\\TC-108943\\TC-108943\\ProjectSuite\\ProjectSuite.pjs"
      
      ACCESS_KEY: ${{ secrets.SMARTBEAR_ACCESS_KEY }}
      LOG_DIR: "${{ github.workspace }}\\logs"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Logs Folder
        run: |
          if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
        shell: cmd

      - name: Run TestExecute
        run: |
          echo Starting TestExecute...
          "C:\Program Files (x86)\SmartBear\TestExecute 15\x64\Bin\TestExecute.exe" ^
            "%PROJECT_PATH%" /r /e ^
            /AccessKey:%ACCESS_KEY% ^
            /SilentMode /Timeout:1200 ^
            /ns ^
            /ErrorLog:"%LOG_DIR%\error.log" ^
            /ExportLog:"%LOG_DIR%\runlog.html" ^
            /ExportSummary:"%LOG_DIR%\runlog.xml" ^
            /shr:"%LOG_DIR%\shared-repo-link.txt" ^
            /shrn:LogFromGitHubAction ^
            /shrei:7
        shell: cmd

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: testexecute-logs
          path: logs
