name: Run Desktop UI Tests with TestExecute

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Set PowerShell Execution Policy
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
          
      - name: Set up environment
        run: |
          echo "Setting up environment variables"
          # Set any necessary environment variables here (if needed)
      - name: Set TestExecute permissions
        run: |
          $path = "C:\Program Files (x86)\SmartBear\TestExecute 15\Bin"
          icacls $path /grant "Everyone:(OI)(CI)F" /T
          icacls "$path\TCHookX86.exe" /grant "Everyone:F"
        shell: powershell
  
      - name: Run TestExecute tests
        run: |
          echo "Starting TestExecute test..."
          & "C:\Program Files (x86)\SmartBear\TestExecute 15\x64\Bin\TestExecute.exe" "C:\actions-runner\_work\TC-108943\TC-108943\ProjectSuite\ProjectSuite.pjs" /r /p:TestProject1
          echo "TestExecute test completed."
        timeout-minutes: 3  # Timeout after 3 minutes (adjust as needed)

