name: Run Desktop UI Tests with TestExecute

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up environment
        run: |
          echo "Setting up environment variables"
          # Set any necessary environment variables here (if needed)
          
      - name: Run TestExecute tests
        run: |
          # Command to run TestExecute with your test project
          cmd.exe /c ""C:\Program Files (x86)\SmartBear\TestExecute 15\x64\Bin\TestExecute.exe" "C:\actions-runner\_work\TC-108943\TC-108943\ProjectSuite\ProjectSuite.pjs" /r /p:TestProject1"
          - name: Run TestExecute tests
